Initial commit
ulixes-bloom/ya-gophermart pull request #1
Opened 2024-12-16 19:07 UTC by ulixes-bloom

2024-12-21 23:12 UTC, bulbetski requested changes
Написано хорошо, но есть пара замечаний, требующих исправления

2024-12-21 23:12 UTC, bulbetski commented on internal/app/accrual.go
> +}
Это надо сделать мапой. Значение мапы будет пустая структура, т.к. она не занимает места в памяти при инициализации

var NotProcessedOrderStatuses map[models.OrderStatus]struct{}

2024-12-21 23:12 UTC, bulbetski commented on api/gophermart/api.go
> +	go a.updateNotProcessedOrders(ctx)
для gracefull shutdown'a надо добавить WaitGroup в обе горутины

2024-12-21 23:12 UTC, bulbetski commented on api/gophermart/api.go
> +	go a.updateNotProcessedOrders(ctx)
Вторую сделать через closure, а не передавать внутрь функции wg

2024-12-21 23:12 UTC, bulbetski commented on api/gophermart/handler/balance.go
> +	userID := req.Context().Value(middleware.UserIDContext).(int64)
Приведение типов вызывает панику в случае неправильного типа. 
То есть надо обязательно делать:
```
userID, ok := req.Context().Value(middleware.UserIDContext).(int64)
if !ok {

}
```
по желанию вынести в хэндлер

2024-12-21 23:12 UTC, bulbetski commented on api/gophermart/handler/balance.go
> +	rw.Write(bufBalance.Bytes())
не обрабатываем ошибку

2024-12-21 23:12 UTC, bulbetski commented on api/gophermart/handler/balance.go
> +	dec := json.NewDecoder(req.Body)
Хорошей практикой является проверка наличия тела запроса
```
if req.Body == nil {
    h.Error(rw, nil, "request body is missing", http.StatusBadRequest)
    return
}
```

2024-12-21 23:12 UTC, bulbetski commented on api/gophermart/handler/interfaces.go
> +	WithdrawFromUserBalance(withdrawalReq *models.WithdrawalRequest, userID int64) error
вкусовщина и практика -- userID как-то заведено первым аргументом писать (если нет контекста)

2024-12-21 23:12 UTC, bulbetski commented on api/gophermart/handler/interfaces.go
> +	RegisterUser(user *models.User) (int64, error)
Поч нигде не передаешь контекст? Он нужен во всех методах и на всех уровнях. При помощи него можно передавать таймауты и сигналы отмены. Контекст можно достать из хттп запроса.

2024-12-21 23:12 UTC, bulbetski commented on api/gophermart/handler/order.go
> +	rw.Write(bufOrders.Bytes())
bytes.Buffer избыточен, так как json.NewEncoder может напрямую писать в http.ResponseWriter

2024-12-21 23:12 UTC, bulbetski commented on api/gophermart/handler/order.go
> +				appErrors.ErrOrderWasUploadedByCurrentUser.Error(),
вот тут копипаста, должно быть ErrOrderWasUploadedByAnotherUser, а у тебя ErrOrderWasUploadedByCurrentUser

2024-12-21 23:12 UTC, bulbetski commented on api/gophermart/handler/user.go
> +	if user.Login == "" || user.Password == "" {
Проверку кредов можно вынести в хелпер

2024-12-21 23:12 UTC, bulbetski commented on api/gophermart/middleware/auth.go
> +		return http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
Трудно читается, можно разбить и будет покрасивше:
```
authHeader := req.Header.Get("Authorization")
if !strings.HasPrefix(authHeader, "Bearer ") {
    log.Error().Msg(appErrors.ErrUserUnauthorized.Error())
    http.Error(rw, appErrors.ErrUserUnauthorized.Error(), http.StatusUnauthorized)
    return
}

jwtToken := strings.TrimPrefix(authHeader, "Bearer ")
if jwtToken == "" {
    log.Error().Msg(appErrors.ErrUserUnauthorized.Error())
    http.Error(rw, appErrors.ErrUserUnauthorized.Error(), http.StatusUnauthorized)
    return
}
```

2024-12-21 23:12 UTC, bulbetski commented on internal/workerpool/workerpool.go
> +func (p *pool[T]) startWorker() {
надо, чтобы обратывался контекст
```
for {
		select {
		case <-ctx.Done():
			// Завершение работы при отмене контекста
			return
		case job, ok := <-p.jobCh:
			if !ok {
				// Если канал job'ов закрыт, завершаем воркер
				return
			}
			
//			остальной код
			```

2024-12-21 23:12 UTC, bulbetski commented on internal/accrual/client.go
> +	}
Здесь &order — это указатель на одну и ту же переменную order, которая изменяется на каждой итерации цикла for. Это значит, что каждая горутина, получившая этот указатель, будет работать с одним и тем же объектом в памяти, который может уже быть изменён при следующей итерации цикла.

В Go переменная order внутри цикла for переиспользуется для каждой итерации.
Когда ты берёшь адрес этой переменной (&order), все указатели фактически ссылаются на одну и ту же область памяти, которая обновляется при каждой новой итерации.

Передавай сам объект, а не указатель на него
```
for _, order := range orders {
    wp.Submit(order) // Передаём сам объект, а не указатель
}
```
Либо
```
for i := range orders {
    wp.Submit(&orders[i]) // Передаём указатель на элемент массива
}
```

2024-12-21 23:12 UTC, bulbetski commented on internal/accrual/client.go
> +	resp, err := ac.http.Do(req)
Добавь контекст с таймаутом для каждого HTTP-запроса, чтобы избежать бесконечного ожидания ответа.

2024-12-21 23:12 UTC, bulbetski commented on internal/app/accrual.go
> +	}
Можно добавить что-то в духе
```
if len(notProcessedOrders) == 0 {
    log.Info().Msg("no orders with statuses 'new' or 'processing' found")
    return nil
}
```

2024-12-21 23:12 UTC, bulbetski commented on internal/security/jwt.go
> +func ValidateJWTString(tokenString, secretKey string) (bool, error) {
не используется

2024-12-21 23:12 UTC, bulbetski commented on internal/security/jwt.go
> +		return false, errors.New("")
Нет сообщения об ошибке

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/balance.go
> +func (pg *pgstorage) GetBalanceByUser(userID int64) (*models.Balance, error) {
Во все методы добавить контекст и использовать QueryRowContext

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/balance.go
> +		WHERE user_id=$2
Параметр $2 используется для обоих balances.current и WHERE user_id
Надо так
```
UPDATE balances
SET withdrawn = balances.withdrawn + $1, current = balances.current - $1
WHERE user_id = $2
RETURNING current;
```

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/balance.go
> +	}
а на помни, почему мы записываем withdrawals перед проверкой баланса? Мы можем просто поменять методы местами и тогда не будет отрицательных балансов в бд

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/balance.go
> +		RETURNING id;`, userID, orderNumber, sum)
id мы никуда не сохраняем, можно тогда удалить returning

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/order.go
> +		defer rows.Close()
Использование defer rows.Close() внутри цикла for приведёт к тому, что вызовы Close будут выполнены только в конце функции, а не после обработки каждого rows. Это может привести к утечке соединений. Закрывай rows сразу после обработки без defer

```
    if err := rows.Err(); err != nil {
        rows.Close()
        return nil, fmt.Errorf("pg.getOrdersByStatus.rowsErr: %w", err)
    }
    rows.Close()
```

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/order.go
> +		}
в методе UpdateOrders обновляем и баланс. Как-то бы тогда разнести по приватным методам или может назвать по-другому

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/order.go
> +	for _, status := range statuses {
Выполнение одного запроса для каждого статуса неэффективно. Можно объединить запросы через оператор IN.
Выглядеть это будет вот так
```
	query := `
        SELECT number, user_id, status, accrual, uploaded_at
        FROM orders
        WHERE status = ANY($1);`
	rows, err := pg.db.Query(query, pq.Array(statuses))
	if err != nil {
		return nil, fmt.Errorf("pg.getOrdersByStatus.query: %w", err)
	}
	defer rows.Close()
```

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/order.go
> +		RETURNING id;`, userID, orderNumber, "NEW")
Возвращаем id через returning, но не используем результат

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/pg.go
> +func (ps *pgstorage) createTables(ctx context.Context) error {
Так, а миграции не хочешь?

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/users.go
> +	tx, err := pg.db.Begin()
Тут не нужна транзакция

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/users.go
> +		}
Красиво было бы вынести в хэлпер
```
func isUniqueViolation(err error, constraint string) bool {
	if pgError, ok := err.(*pgconn.PgError); ok {
		return pgError.Code == pgerrcode.UniqueViolation && pgError.ConstraintName == constraint
	}
	return false
}
```

2024-12-21 23:12 UTC, bulbetski commented on internal/storage/pg/users.go
> +		RETURNING id;`, id)
В одну и ту же переменную записываем user_id, потом balance_id. Надо отсюда удалить returning, раз метод у нас про юзера

2024-12-27 20:54 UTC, ulixes-bloom commented on api/gophermart/handler/balance.go
> +	rw.Write(bufBalance.Bytes())
поменяла это место, ошибка при кодировании в json обрабатывается

2024-12-27 20:56 UTC, ulixes-bloom commented on api/gophermart/api.go
> +	go a.updateNotProcessedOrders(ctx)
прикольно, действительно горутины завершаются некорректно. даже не подумала
думаю, починила

2024-12-27 21:17 UTC, ulixes-bloom commented on api/gophermart/handler/order.go
> +	rw.Write(bufOrders.Bytes())
да, согласна, поменяла

2024-12-27 21:28 UTC, ulixes-bloom commented on api/gophermart/handler/user.go
> +	if user.Login == "" || user.Password == "" {
добавила функцию checkUserCredentials, так норм? или ты прям про отдельный пакет helpers?

2024-12-27 21:36 UTC, ulixes-bloom commented on api/gophermart/middleware/auth.go
> +		return http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
согласна, поменяла тут код

2024-12-27 21:40 UTC, ulixes-bloom commented on internal/security/jwt.go
> +		return false, errors.New("")
Убрала эту функцию ValidateJWTString

2024-12-27 21:44 UTC, ulixes-bloom commented on internal/storage/pg/balance.go
> +		WHERE user_id=$2
заметила этот косяк в тестах, поправила

2024-12-29 17:41 UTC, ulixes-bloom commented on internal/storage/pg/balance.go
> +	}
да, так лучше, пожалуй, ошибка с отрицательным балансом выпадет раньше. но сейчас код тож работает, тк изменения в бд идут в рамках одной транзакции

2024-12-29 18:08 UTC, ulixes-bloom commented on internal/storage/pg/order.go
> +		}
Переименовала метод
Не стала разносить в разные функции, тк кажется, это лучше делать в одной транзакции. Ну или я не понимаю, как это можно красиво разнести

2024-12-29 18:09 UTC, ulixes-bloom commented on internal/storage/pg/order.go
> +	for _, status := range statuses {
да, прикольно. забываю, что sql тоже умеет упрощать жизнь

2024-12-29 18:18 UTC, ulixes-bloom commented on internal/storage/pg/pg.go
> +func (ps *pgstorage) createTables(ctx context.Context) error {
в курсе не было про миграции бд 🥲
но тема и идея для доработки хорошая, за каникулы попробую прикрутить

2024-12-29 21:31 UTC, ulixes-bloom commented on internal/workerpool/workerpool.go
> +func (p *pool[T]) startWorker() {
добавила контекст в worker pool, контекст прокидываю через метод new в startWorker, потому что где-то встречала, что контекст не рекомендуется сохранять в структуру

2024-12-29 21:39 UTC, ulixes-bloom commented on api/gophermart/handler/interfaces.go
> +	RegisterUser(user *models.User) (int64, error)
добавила контекст, забираю его из хттп запроса в хендлерах
таймаут добавила только в контекст, который используется в accrual клиенте (там где по http запрашивается информация о заказах в стороннем сервисе accrual)
есть смысл для всех хендлеров назначить таймаут в контексте или это излишне?

2024-12-29 22:22 UTC, ulixes-bloom commented on internal/accrual/client.go
> +	}
эх, дурацкая ошибка( спасибо, что заметил
поправила

2024-12-29 22:26 UTC, ulixes-bloom commented on internal/app/accrual.go
> +}
я что-то не поняла, зачем здесь мапа?) я использую этот список, чтобы из бд выгружать заказы с необработанным статусом. кажется, список тут идеально подходит

2025-01-09 16:44 UTC, bulbetski commented on internal/app/accrual.go
> +}
действительно незачем. Просто на случай, если бы нам приходилось делать какие-то проверки, приходилось бы по массиву итерировать. И как правило, чтобы не итерировать по какому-нибудь массиву констант, используют мапу.

2025-01-09 16:45 UTC, bulbetski commented on api/gophermart/handler/balance.go
> +			http.StatusInternalServerError)
ну это скорее bad request

2025-01-09 16:49 UTC, bulbetski commented on api/gophermart/handler/interfaces.go
> +	RegisterUser(user *models.User) (int64, error)
есть смысл назначать таймаут только в местах, где ты хочешь, чтобы таймаут произошел. Так же его стоит как бы передавать только в определенное место. К примеру, у тебя в твоей ручке происходит 1 запрос во внешний сервис и один запрос в БД, ты можешь не хочеть таймаут на бд и хотеть таймаут на хттп (или наоборот), поэтому сделаешь таймаут не на контекст всего метода, а только на контекст, который передашь в хттп запрос

2025-01-09 16:51 UTC, bulbetski commented on api/gophermart/handler/user.go
> +	if user.Login == "" || user.Password == "" {
Вполне норм. Хелперы как правило в отдельный пакет не выносят. Хелперы -- фукнции имеющие привязку к пакету, помогают упростить какую-то бизнес тему.
Отдельным пакетом делают utils, туда пихают какую-нибудь математику, работу с временем, конвертации базовых типов, работу со строками итд. То есть то, что можно применить везде вне зависимости от того, что делает пакет

2025-01-09 16:51 UTC, bulbetski commented on internal/workerpool/workerpool.go
> +func (p *pool[T]) startWorker() {
всё верно

2025-01-09 16:54 UTC, bulbetski commented on internal/storage/pg/order.go
> +		}
Норм

2025-01-09 16:55 UTC, bulbetski approved these changes
Всё круто написала и исправила

2025-01-11 11:49 UTC, merged